---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: messenger
  name: messenger
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messenger
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: messenger
    spec:
      containers:
      - name: messenger
        image:  imauld/messenger:app-0.2.3
        imagePullPolicy: IfNotPresent
        command: 
          - "./venv/bin/python"
        args:
          - app/server.py
        ports:
          - containerPort: 8081
      dnsPolicy: ClusterFirst
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: messenger
spec:
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
  selector:
    app: messenger
  type: NodePort
